// Catalog entries introduced by the six-block strength periodization (weeks
// 6–35). Equipment stays minimal: mat, 2×12.5 kg dumbbells, pull-up bar, and
// a chair/step/sofa for step-ups, Copenhagens, RFESS and Nordic anchoring.

import type { StrengthExerciseCatalogEntry } from '../types'

export const BLOCK_EXERCISES: StrengthExerciseCatalogEntry[] = [
  {
    id: 'box-goblet-squat',
    name: 'Box goblet squat',
    targetArea: 'Quads/glutes',
    equipment: 'dumbbell',
    formCue: 'Sit back to a chair or box on a 3-second lower, pause 1 s, stand in 1 s.',
    cues: [
      'Hold one dumbbell at the chest, elbows pointing down.',
      'Lower for 3 s until you lightly touch the box — don’t flop onto it.',
      'Pause 1 s with tension kept, then drive up through mid-foot in 1 s.',
    ],
    commonMistake: 'Sitting down fully and relaxing on the box, which removes the pause’s strength stimulus.',
    easierVariation: 'Use a higher box or no dumbbell.',
    harderVariation: 'Lower the box, or lengthen the lowering phase to 4 s.',
  },
  {
    id: 'db-rdl',
    name: 'Dumbbell Romanian deadlift',
    targetArea: 'Hamstrings/glutes',
    equipment: 'dumbbell',
    formCue: 'Soft knees, push the hips back, keep the dumbbells close to the legs.',
    cues: [
      'Start tall with a dumbbell in each hand, knees soft.',
      'Push the hips back until you feel the hamstrings stretch — the back stays flat.',
      'Drive the hips forward to stand, squeezing the glutes at the top.',
    ],
    commonMistake: 'Rounding the back or turning it into a squat by bending the knees too much.',
    easierVariation: 'Shorter range — stop at mid-shin.',
    harderVariation: 'Slow 3-second lower, or pause just below the knee.',
  },
  {
    id: 'seated-soleus-raise',
    name: 'Seated bent-knee soleus raise',
    targetArea: 'Soleus/Achilles',
    equipment: 'dumbbell',
    formCue: 'Seated, knees at 90° with dumbbells on the thighs; raise the heels high and lower slowly.',
    cues: [
      'Sit on a chair with feet flat, dumbbells resting on the knees.',
      'Rise onto the balls of the feet as high as you can.',
      'Lower for a slow 2–3 count to full stretch.',
    ],
    commonMistake: 'Bouncing through a short range instead of full, controlled reps.',
    easierVariation: 'No dumbbells, or one dumbbell across both knees.',
    harderVariation: 'Single-leg, with both dumbbells on one knee.',
  },
  {
    id: 'push-up',
    name: 'Push-up',
    targetArea: 'Chest/triceps/core',
    equipment: 'bodyweight',
    formCue: 'Straight line from head to heels; hands under shoulders. Use an incline if you can’t get 8 reps.',
    cues: [
      'Brace the core and squeeze the glutes so the hips don’t sag.',
      'Lower the chest to just above the floor, elbows at ~45°.',
      'Press the floor away to full lockout.',
    ],
    commonMistake: 'Letting the hips sag or flaring the elbows straight out to the sides.',
    easierVariation: 'Hands on a sofa arm or bench (incline) if you get fewer than 8 reps.',
    harderVariation: 'Slow 3-second lower.',
  },
  {
    id: 'push-up-feet-elevated',
    name: 'Feet-elevated push-up',
    targetArea: 'Chest/shoulders/core',
    equipment: 'chair',
    formCue: 'Feet on a chair or step, body in one line; lower under control.',
    cues: [
      'Place the feet on a step or chair, hands under shoulders.',
      'Keep ribs down and glutes tight — no pike or sag.',
      'Lower the chest to just above the floor and press back up.',
    ],
    commonMistake: 'Piking the hips up to make the movement easier.',
    easierVariation: 'Regular floor push-up.',
    harderVariation: 'Higher foot position or a 3-second lower.',
  },
  {
    id: 'push-up-decline-tempo',
    name: 'Decline tempo push-up',
    targetArea: 'Chest/shoulders/core',
    equipment: 'chair',
    formCue: 'Feet elevated; 3-second lower, 1-second pause just off the floor, push up.',
    cues: [
      'Feet on a chair, body rigid from head to heels.',
      'Count 3 on the way down, hold 1 just off the floor.',
      'Press up smoothly without losing the plank.',
    ],
    commonMistake: 'Rushing the lowering phase, which loses the tempo stimulus.',
    easierVariation: 'Feet-elevated push-ups at normal tempo.',
    harderVariation: 'Add a 2-second pause at the bottom.',
  },
  {
    id: 'push-up-archer',
    name: 'Archer push-up',
    targetArea: 'Chest/triceps (unilateral bias)',
    equipment: 'bodyweight',
    formCue: 'Wide hands; shift your weight to one arm as the other straightens out to the side.',
    cues: [
      'Set the hands wider than a normal push-up.',
      'Lower toward one hand while the other arm straightens along the floor.',
      'Press back to the middle and alternate sides.',
    ],
    commonMistake: 'Twisting the hips instead of keeping the body square to the floor.',
    easierVariation: 'Decline tempo push-ups.',
    harderVariation: 'Slow the lowering to 3 s on each side.',
  },
  {
    id: 'side-lying-hip-abduction',
    name: 'Side-lying hip abduction',
    targetArea: 'Glute medius',
    equipment: 'mat',
    formCue: 'Lying on your side, lift the top leg slightly behind the body, toes pointing forward.',
    cues: [
      'Stack the hips and keep the top leg straight.',
      'Lead with the heel, leg slightly behind the body line.',
      'Lift to about 30°, pause, and lower slowly.',
    ],
    commonMistake: 'Rolling the hips back and lifting with the hip flexor instead of the glute.',
    easierVariation: 'Smaller range of motion.',
    harderVariation: '2-second hold at the top of each rep.',
  },
  {
    id: 'step-up',
    name: 'Step-up',
    targetArea: 'Quads/glutes',
    equipment: 'chair',
    formCue: 'Whole foot on a knee-height step; drive up through the front heel without pushing off the back foot.',
    cues: [
      'Place the entire foot on the step, knee over the foot.',
      'Stand up by pushing through the front heel, not by bouncing off the back leg.',
      'Lower slowly under control, same leg for all reps.',
    ],
    commonMistake: 'Pushing off the back foot so the working leg does half the job.',
    easierVariation: 'Lower step.',
    harderVariation: 'Hold a dumbbell in each hand.',
  },
  {
    id: 'copenhagen-short',
    name: 'Copenhagen plank (short lever)',
    targetArea: 'Adductors/groin',
    equipment: 'chair',
    formCue: 'Side plank with the top knee on a chair or sofa; lift the hips into a straight line.',
    cues: [
      'Rest the inside of the top knee on the chair, forearm under the shoulder.',
      'Squeeze the top leg down into the chair to lift the hips.',
      'Hold a straight line from head to knee, breathing steadily.',
    ],
    commonMistake: 'Letting the hips sag or rotate forward.',
    easierVariation: 'Shorter holds (10 s), or the bottom foot lightly on the floor.',
    harderVariation: 'Longer holds, or progress to the long-lever version.',
  },
  {
    id: 'copenhagen-long',
    name: 'Copenhagen plank (long lever)',
    targetArea: 'Adductors/groin',
    equipment: 'chair',
    formCue: 'Side plank with the top ankle on the chair; lift the hips and hold a straight line.',
    cues: [
      'Place the inside of the top ankle/foot on the chair.',
      'Press the top leg down to lift the hips off the floor.',
      'Keep the body in one line; stop the set if you feel groin pain.',
    ],
    commonMistake: 'Rushing into long holds — this version loads the groin much more.',
    easierVariation: 'Short-lever version (knee on the chair).',
    harderVariation: 'Slowly lift and lower the bottom leg while holding.',
  },
  {
    id: 'double-leg-calf-raise',
    name: 'Double-leg calf raise',
    targetArea: 'Calves',
    equipment: 'bodyweight',
    formCue: 'Straight knees, rise high onto the balls of both feet, lower slowly.',
    cues: [
      'Hold a wall or chair lightly for balance.',
      'Rise straight up, weight over the big toe.',
      'Lower for a slow 2–3 count.',
    ],
    commonMistake: 'Bouncing through half reps.',
    easierVariation: 'Smaller range.',
    harderVariation: 'Hold dumbbells, or move to single-leg.',
  },
  {
    id: 'rfess',
    name: 'Rear-foot-elevated split squat',
    targetArea: 'Quads/glutes',
    equipment: 'chair',
    formCue: 'Back foot laces-down on a chair; lower straight down until the back knee nearly touches.',
    cues: [
      'Stand about a stride in front of the chair, rear foot laces-down on it.',
      'Lower straight down with the torso tall, front shin close to vertical.',
      'Drive through the front heel to stand.',
    ],
    commonMistake: 'Standing too close to the chair so the front knee shoots far past the toes.',
    easierVariation: 'Split squat with the back foot on the floor.',
    harderVariation: 'Hold a dumbbell in each hand.',
  },
  {
    id: 'rfess-pause',
    name: 'RFESS with 2 s pause',
    targetArea: 'Quads/glutes',
    equipment: 'chair',
    formCue: 'As RFESS, holding 2 seconds at the bottom before driving up.',
    cues: [
      'Rear foot laces-down on the chair, dumbbells in hand.',
      'Lower to just above the floor and hold still for 2 s.',
      'Drive up through the front heel without bouncing.',
    ],
    commonMistake: 'Relaxing at the bottom and losing tension during the pause.',
    easierVariation: 'Bodyweight, or a 1-second pause.',
    harderVariation: 'Heavier dumbbells (top of range at RPE ≤8 first).',
  },
  {
    id: 'rfess-explosive',
    name: 'RFESS, explosive up',
    targetArea: 'Quads/glutes/power',
    equipment: 'chair',
    formCue: 'Controlled 2-second lower, then stand up as fast as possible.',
    cues: [
      'Lower under control for 2 s.',
      'Drive up explosively — intent matters more than load.',
      'Reset balance between reps; quality over quantity.',
    ],
    commonMistake: 'Letting the lowering phase get sloppy while chasing speed.',
    easierVariation: 'Bodyweight only.',
    harderVariation: 'Light dumbbells while keeping the speed.',
  },
  {
    id: 'nordic-curl',
    name: 'Nordic curl (regression)',
    targetArea: 'Hamstrings',
    equipment: 'chair',
    formCue: 'Kneeling with heels anchored under a sofa; lower forward slowly through a partial range, catch with hands.',
    cues: [
      'Kneel on a mat with the heels hooked under a heavy sofa.',
      'Keep a straight line from knees to head and lower forward as slowly as you can.',
      'Stop at the range you control, catch yourself with your hands, push back up.',
    ],
    commonMistake: 'Bending at the hips to shorten the lever instead of lowering with the hamstrings.',
    easierVariation: 'Smaller range — just lean forward a little and return.',
    harderVariation: 'Lower through a longer range before catching.',
  },
  {
    id: 'weighted-dead-bug',
    name: 'Weighted dead bug',
    targetArea: 'Core/anti-extension',
    equipment: 'dumbbell',
    formCue: 'Dead bug holding a dumbbell over the chest; the low back stays pressed into the mat.',
    cues: [
      'Hold one dumbbell with straight arms above the chest.',
      'Lower the opposite arm and leg slowly while the back stays flat.',
      'Exhale as you extend.',
    ],
    commonMistake: 'Letting the low back arch as the leg lowers.',
    easierVariation: 'Unweighted dead bug.',
    harderVariation: 'Slower tempo or a longer lever (straight leg).',
  },
  {
    id: 'hollow-hold',
    name: 'Hollow hold',
    targetArea: 'Core',
    equipment: 'mat',
    formCue: 'Lying on your back, low back pressed down, lift the shoulders and legs and hold.',
    cues: [
      'Press the low back into the mat before lifting.',
      'Lift shoulders and legs a few inches, arms reaching long.',
      'Hold while breathing — bend the knees to make it easier.',
    ],
    commonMistake: 'Letting the low back peel off the mat.',
    easierVariation: 'Knees bent (tuck hollow).',
    harderVariation: 'Arms overhead and legs lower.',
  },
  {
    id: 'body-saw',
    name: 'Body saw',
    targetArea: 'Core/anti-extension',
    equipment: 'mat',
    formCue: 'From a forearm plank, rock the body forward and back a few inches without the hips sagging.',
    cues: [
      'Set up in a forearm plank with feet on a towel or smooth floor.',
      'Shift the body back past the elbows, then forward again.',
      'Move only as far as you can keep a straight line.',
    ],
    commonMistake: 'Sagging at the hips as the lever lengthens.',
    easierVariation: 'Smaller range, or from the knees.',
    harderVariation: 'Slower, longer range.',
  },
  {
    id: 'deficit-calf-raise',
    name: 'Small-deficit single-leg calf raise',
    targetArea: 'Calves/Achilles',
    equipment: 'chair',
    formCue: 'Ball of the foot on a low step edge; lower slightly below level, rise high — never forcing full toe extension.',
    cues: [
      'Stand on one foot on a low step, heel off the edge.',
      'Lower just below the step (a small deficit), then rise high.',
      'Keep the knee straight and hold a wall for balance.',
    ],
    commonMistake: 'Dropping deep into the deficit or rising onto fully bent toes.',
    easierVariation: 'Flat-floor single-leg calf raise.',
    harderVariation: 'Hold a dumbbell on the working side.',
  },
  {
    id: 'weighted-pull-up',
    name: 'Weighted pull-up',
    targetArea: 'Back/biceps',
    equipment: 'pullup-bar',
    formCue: 'Pull-ups holding a dumbbell between the feet; full hang to chin over the bar.',
    cues: [
      'Grip a dumbbell between the feet (or skip the weight if reps drop below 3).',
      'Pull the elbows down and back until the chin clears the bar.',
      'Lower under control to a full hang.',
    ],
    commonMistake: 'Swinging or kipping to get the weight up.',
    easierVariation: 'Bodyweight pull-ups.',
    harderVariation: 'Slow 3-second lowering.',
  },
  {
    id: 'plyo-primer',
    name: 'Plyo primer: pogo hops + A-skips',
    targetArea: 'Elastic stiffness/running mechanics',
    equipment: 'bodyweight',
    formCue: 'Quick, stiff-ankle pogo hops, then rhythmic A-skips — crisp and light, never to fatigue.',
    cues: [
      'Pogos: small hops off the balls of the feet, minimal knee bend, short ground contact.',
      'A-skips: drive the knee up, strike down under the hips, stay tall.',
      'Stop if contacts get heavy or noisy.',
    ],
    commonMistake: 'Letting the heels crash down or turning pogos into big jumps.',
    easierVariation: 'Fewer contacts, or marching A-drills instead of skips.',
  },
  {
    id: 'plyo-power',
    name: 'Plyos: single-leg pogos + low step jumps',
    targetArea: 'Power/elastic stiffness',
    equipment: 'chair',
    formCue: 'Single-leg pogos and jumps onto a low step with quiet, stable landings — cap total contacts.',
    cues: [
      'Single-leg pogos: short contacts, knee soft but stable.',
      'Step jumps: jump onto a low step, land softly, step down.',
      'Full recovery between sets — quality, not conditioning.',
    ],
    commonMistake: 'Chasing more contacts once landings get sloppy.',
    easierVariation: 'Double-leg pogos.',
  },
  {
    id: 'glute-bridge',
    name: 'Glute bridge',
    targetArea: 'Glutes',
    equipment: 'mat',
    formCue: 'Both feet planted; drive the hips up by squeezing the glutes, ribs down.',
    cues: [
      'Feet hip-width, heels close to the glutes.',
      'Drive through the heels and squeeze the glutes at the top.',
      'Lower slowly without arching the back.',
    ],
    commonMistake: 'Over-arching the back instead of finishing with the glutes.',
    harderVariation: 'Single-leg glute bridge.',
  },
]
